// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package controllers

import (
	"notify/internal"
)

// Injectors from wire.go:

func initControllers(app *notify.App) *Controllers {
	pingController := providePingController(app)
	callbackController := provideCallbackController(app)
	controllers := &Controllers{
		App:  app,
		Ping: pingController,
		Call: callbackController,
	}
	return controllers
}
