// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package infra

import (
	"code.jshyjdtech.com/godev/hykit/container"
	"code.jshyjdtech.com/godev/hykit/grpc"
)

// Injectors from wire.go:

func initInfra(esim *container.Esim, grpc2 *grpc.Client) *Infra {
	client := provideDb(esim)
	redisClient := provideRedis(esim)
	infra := &Infra{
		Esim:        esim,
		DB:          client,
		RedisClient: redisClient,
	}
	return infra
}
