package resp_code

const (
	SUCCESS           = "0000"
	SYSTEMERR         = "SYSTEMERR"
	INVALID_PARAMETER = "INVALID_PARAMETER"
	FORMAT_ERR        = "FORMAT_ERR"
	MSGFLDERR         = "MSGFLDERR"
	AESDECRYPTERR     = "AESDECRYPTERR"
	KEYERROR          = "KEYERROR"
	SIGNERR           = "SIGNERR"
	DECERR            = "DECERR"
	APPERR            = "APPERR"
	MCHTERR           = "MCHTERR"
	PRODAUTHERR       = "PRODAUTHERR"
	BALERR            = "BALERR"
	EXTREGERR         = "EXTREGERR"
	FEECDERR          = "FEECDERR"
	USERMODERR        = "USERMODERR"
	USERIDERR         = "USERIDERR"
	USERNOTFOUND      = "USERNOTFOUND"
	USERNAMEERR       = "USERNAMEERR"
	USERCERTERR       = "USERCERTERR"
	ACCTNOERR         = "ACCTNOERR"
	ACCTPRODERR       = "ACCTPRODERR"
	ACCSUPPORTERR     = "ACCSUPPORTERR"
	TOKENEXPERR       = "TOKENEXPERR"
	CARDBINERR        = "CARDBINERR"
	USERFEEERR        = "USERFEEERR"
	MCHTFEEERR        = "MCHTFEEERR"
	APPFEEERR         = "APPFEEERR"
	AMOUNTERR         = "AMOUNTERR"
	AMTNOTENG         = "AMTNOTENG"  //余额不足
	AMTRISKERR        = "AMTRISKERR" //风控限额
	RISKERR           = "RISKERR"    //风控限额
	AMTLIMERR         = "AMTLIMERR"  //风控限额
	INVALIDTMERR      = "INVALIDTMERR"
	ROUTEERR          = "ROUTEERR"
	INVALIDPROTO      = "INVALIDPROTO"
	TIMEOUT           = "TIMEOUT"
	COMMERR           = "COMMERR" //渠道通信失败
	RECORDNOTFOUND    = "RECORDNOTFOUND"
	ORIGTRANERR       = "ORIGTRANERR"
	FETORGERR         = "FETORGERR"
	RECORDDUPLICATE   = "RECORDDUPLICATE"
	CHNLERR           = "CHNLERR"       //渠道异常
	PAYISSERR         = "PAYISSERR"     //支付通道异常
	AUTHERR           = "AUTHERR"       //鉴权失败
	ACCVERIERR        = "ACCVERIERR"    //用户信息鉴权失败
	TRANERR           = "TRANERR"       //支付失败
	INVALIDACCTTP     = "INVALIDACCTTP" //非法卡类型
	SMSAUTHERR        = "SMSAUTHERR"    //短信验证码校验失败
	SMSTIMEOUT        = "SMSTIMEOUT"    //验证码已失效
	PHONEERR          = "PHONEERR"      //手机号码校验失效
	SMSRETRYERR       = "SMSRETRYERR"   //验证码重试次数过多
	SMSSNDERR         = "SMSSNDERR"     //验证码发送失败
	ACCTCANCELED      = "ACCTCANCELED"  //卡已注销
	ACCTSTATERR       = "ACCTSTATERR"   //卡状态异常
	ACCTEXPIRERR      = "ACCTEXPIRERR"  //卡状态异常
	ACCTRISKERR       = "ACCTRISKERR"   //该卡有风险
	CERTIDERR         = "CERTIDERR"     //身份证号验证失败
	TRANCNTLIMT       = "TRANCNTLIMT"   //交易次数超限制
	PWDCNTLIMT        = "PWDCNTLIMT"    //密码输入次数超限
	NEEDPWDAUTH       = "NEEDPWDAUTH"   //密码输入次数超限
	BINDERR           = "BINDERR"       //绑卡失败
	RFNDPROC          = "RFNDPROC"      //退款处理中
	RFNDBANKP         = "RFNDBANKP"     //银行处理中
	TRANINPROC        = "TRANINPROC"    //支付处理中
	CHECKOUTINP       = "CHECKOUTINP"   //扣款成功，销账未知
	CHECKOUTERR       = "CHECKOUTERR"   //扣款成功，销账失败
	FILENOTEXIST      = "FILENOTEXIST"  //文件不存在

	TASKNOFINISH = "TASKNOFINISH" //任务未完成
)
